services:
  analyzer:
    image: local/analyzer:v1
    build: ./
    container_name: trisda_dev_analyzer
    #ports:
    #  - "9000:9000"
    networks:
      - trisda_dev_internal
    healthcheck:
      test: curl --fail -s http://localhost:9000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
networks:
  trisda_dev_internal:
    external: true
